# Generated by Django 3.1.6 on 2021-02-07 06:21

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=32)),
                ('Student_Reg_No', models.IntegerField(unique=True)),
                ('Email', models.EmailField(max_length=100, unique=True,default=uuid.uuid4)),
            ],
        ),
    ]
