# Generated by Django 3.1.6 on 2021-02-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                #('Answer', models.CharField(max_length=50)),
            ],
        ),
    ]
