# Generated by Django 3.1.6 on 2021-02-10 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExam', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Answer',
            field=models.CharField(default=datetime.time, max_length=50),
            preserve_default=False,
        ),
    ]
