# Generated by Django 3.1.6 on 2021-02-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExam', '0004_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Email',
        ),
    ]
