# Generated by Django 3.1.6 on 2021-02-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExam', '0006_auto_20210217_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Answer',
            field=models.CharField(max_length=100),
        ),
    ]
