# Generated by Django 3.1.6 on 2021-02-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExam', '0009_question_answer1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Answer',
        ),
    ]
