# Generated by Django 3.1.6 on 2021-02-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExam', '0011_auto_20210220_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option1',
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.BooleanField(default=False),
        ),
    ]
