# Generated by Django 3.1.6 on 2021-02-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExam', '0012_auto_20210221_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(max_length=100),
        ),
    ]
