# Generated by Django 3.1.6 on 2021-02-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExam', '0013_auto_20210221_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_Reg_No',
            field=models.IntegerField(default='HC', unique=True),
        ),
    ]
