# Generated by Django 3.1.6 on 2021-02-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExam', '0014_auto_20210222_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_Reg_No',
            field=models.CharField(default='HC', max_length=10, unique=True),
        ),
    ]
