# Generated by Django 3.1.6 on 2021-03-08 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineExam', '0015_auto_20210222_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Answer1',
        ),
        migrations.AddField(
            model_name='question',
            name='Answer',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
